version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  web:
    image: pickmybruin/backend:latest
    command: bash initialize.sh
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

