version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
  websockets:
    image: bquest/websockets:latest
    build: websockets
    ports:
      - "8001:80"
  web:
    image: bquest/backend:latest
    build: .
    command: bash initialize.sh
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - websockets

